-- Account: ad2c12ed-816b-4354-98ed-53a47410999b at 2026-05-18T10:50:03.469616
-- Commit message: test

SELECT
  c.C_CUSTKEY,
  c.C_NAME,
  c.C_MKTSEGMENT,
  c.C_ACCTBAL,
  o.O_ORDERKEY,
  o.O_ORDERDATE,
  o.O_TOTALPRICE,
  o.O_ORDERSTATUS,
  o.O_ORDERPRIORITY,
  l.L_LINENUMBER,
  l.L_QUANTITY,
  l.L_EXTENDEDPRICE,
  l.L_DISCOUNT,
  l.L_TAX,
  l.L_RETURNFLAG,
  l.L_LINESTATUS,
  l.L_SHIPDATE,
  s.S_NAME,
  s.S_ACCTBAL
FROM
  SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER c
  INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS o ON c.C_CUSTKEY = o.O_CUSTKEY
  INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY
  INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER s ON l.L_SUPPKEY = s.S_SUPPKEY